with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;

package LZWL is

   -- LZWL uses syllables instead of characters as the foundational data unit.
   type Syllable_Array is array (Positive range <>) of Unbounded_String;
   
   -- Codes generated by the dictionary mapped sequentially
   type Code is new Natural;
   type Code_Array is array (Positive range <>) of Code;
   
   -- Exception for bounds, unknown syllables, and corrupt data streams
   LZWL_Error : exception;

   -- =========================================================================
   -- Variant 1: Basic Syllable-Based Adaptation
   -- =========================================================================
   -- Implements standard LZWL handling, where the input stream is treated 
   -- as a sequence of predefined syllables.
   procedure Encode_Basic (
      Alphabet   : in Syllable_Array;
      Input      : in Syllable_Array;
      Output     : out Code_Array;
      Output_Len : out Natural);
      
   procedure Decode_Basic (
      Alphabet   : in Syllable_Array;
      Input      : in Code_Array;
      Output     : out Syllable_Array;
      Output_Len : out Natural);

   -- =========================================================================
   -- Variant 2: Dictionary Expansion Variant
   -- =========================================================================
   -- Modifies the dictionary addition logic to prevent forming strings from 
   -- syllables that only appear once, heavily optimizing specific payloads.
   procedure Encode_Expanded (
      Alphabet   : in Syllable_Array;
      Input      : in Syllable_Array;
      Output     : out Code_Array;
      Output_Len : out Natural);
      
   procedure Decode_Expanded (
      Alphabet   : in Syllable_Array;
      Input      : in Code_Array;
      Output     : out Syllable_Array;
      Output_Len : out Natural);

end LZWL;
